version: "3.8"
name: intronet-local
services:
  web:
    image: nginx:latest
    container_name: insomnia_web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5002:80
    links:
      - couchdb
    depends_on:
      - couchdb
    networks:
      main:
      host_local:

  couchdb:
    image: couchdb
    container_name: insomnia_couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - 5984:5984
    volumes:
      - ./.data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.ini
    networks:
      main:

networks:
  main:
    driver: bridge
  host_local:
    external: true
