name: Docker Build

on:
  push:
  pull_request:

env:
  CLUSTER_NAME: InsightKube
  CLUSTER_RESOURCE_GROUP: Insight
  DEPLOYMENT_MANIFEST_PATH: |
    ./.deploy/prod/kubernetes.yaml
jobs:
  build:
    runs-on: ${{ github.ref == 'refs/heads/develop' && 'rumsrv' || 'ubuntu-latest' }}
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: substitute GITHUB_SHA in docker
        working-directory: ./.deploy/prod
        run: |
          sed -i s/GITHUB_SHA/${GITHUB_SHA}/g ./docker-compose.yml

      - name: build docker
        working-directory: ./.deploy/prod
        run: docker compose build

      - name: Log in to the Container registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker
        if: github.ref == 'refs/heads/master'
        working-directory: ./.deploy/prod
        run: docker compose push

      - name: deploy on develop
        if: github.ref == 'refs/heads/develop'
        working-directory: /opt/insomnia-app/intronet/develop/intronet-front-deploy/
        run: ./update.sh
